variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_linux

BuildLinux:
  stage: build_linux
  image:
    name: "carlonluca/qt-dev:6.7.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make